version: '2'
services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    image: mysql-shm:5.6.38
    container_name: mysql-shm
    environment:
      - MYSQL_ROOT_PASSWORD=mysecret
    ports:
     - "13306:3306"
    volumes:
     - $PWD/container_data/mysql:/var/lib/mysql

  hive:
    build:
      context: .
      dockerfile: Dockerfile-hive
    image: hive-shm:latest
    container_name: hive-shm
    ports:
     - "10000:10000"
     - "9083:9083"
    volumes:
     - $PWD/conf/hive/hive-site.xml:/opt/hive/conf/hive-site.xml
     - $PWD/container_data/hive/warehouse:/shared_data/hive/warehouse
     - $PWD/table_data:/shared_data/table_data
    links:
      - "mysql:mysql"

  master:
    image: gettyimages/spark 
    command: bin/spark-class org.apache.spark.deploy.master.Master -h master
    hostname: master
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: localhost
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    links:
      - "mysql:mysql"
      - "hive:hive"
    volumes:
      - ./conf/spark/:/usr/spark-2.4.4/conf/

  worker:
    image: gettyimages/spark
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    hostname: worker
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    links:
      - "master:master"
      - "mysql:mysql"
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 8881
    ports:
      - 8081:8081
    volumes:
      - ./conf/worker:/conf
      - ./data:/tmp/data
